name: github-ci
defaults:
  run:
    shell: bash
    working-directory: ./scripts
on:
  push:
    branches:
      - 'main'
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo code
        uses: actions/checkout@v4
      - name: Run linting script
        shell: bash
        env:
          IP: ${{ secrets.GCP_VM_IP }}
        run: ./lint.sh
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repo code
        uses: actions/checkout@v4
      - name: Deploy to GCE VM
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          script: |
            whoami

  upload:
    runs-on: ubuntu-latest
    needs: [lint, build]
    steps:
      - name: Checkout repo code
        uses: actions/checkout@v4
      - name: Run upload script
        run: ./upload.sh
  deploy:
    runs-on: ubuntu-latest
    needs: [lint, build, upload]
    steps:
      - name: Checkout repo code
        uses: actions/checkout@v4
      - name: Run deploy script
        run: ./deploy.sh
