name: github-ci
defaults:
  run:
    shell: bash
    working-directory: ./scripts
on:
  push:
    branches:
      - 'main'
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo code
        uses: actions/checkout@v4
      - name: Lint, Build, and Deploy App Changes
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_VM_USER }}
          password: ${{ secrets.GCP_SSH_PASSWORD }}
          script: |
            cd /home/dev/CS130-Final-Proj
            git pull
            cd frontend
            npm install
            npm run build
            pkill "next-server"
            npm run start_prd &
